Duplicates:
  fields_to_check:
    - Text
  check_duplicates_tag: Ankisthesia_AnkiHub
  compare_to_tag: "#AK_Step1_v12"
  tags_to_skip: #These only match tags that START with the following
    - Delete
    - Duplicate
    - ~DupCatch_V2

Merge:
  merge_tags: true
  merge_fields: true
  tags_to_ignore: #These match any tags that CONTAIN the followingAaw`ww`2ww  `1ED  `1R 1R
    - ~DupCatch
    - Delete
    - Duplicate
    - flag
    - NotDoing
  fields_to_ignore:
    - Text
    - Front
    - Back
  field_seperator: "<br>"
  merge_suffix: "::merge"
  merge_tags_suffix: "::mtags"
  merge_fields_suffix: "::mfields"
  map_missing_field: Additional Resources
  covered_by_tag: "!Covered_By::(DECK)"
  covered_by_suffix: "::cb"

Remember:
  non_dupes_tag_suffix: "::nd"

Scoring:
  cloze_multiplier: 5                                       #Word-scores will be multiplied by this factor for words inside a cloze
  emphasis_multiplier: 2                                    #words that are inside of an html tag (ie. bold, underline, italics) will be multiplied by this factor
  emphasis_pattern: '[bui]'                                 #pattern to match html tags, default [bui] for bold, underline, and italics
  rare_leveling: 25                                         #higher numbers will score rare words higher
  score_cutoff: 75                                          #Cutoff score to tag pairs
  keep_top: 15                                              #Keep top n cards even if they don't meet score_cutoff
  keep_top_absolute: 5                                      #scores are percentages, but this will keep the top absolute (non-percentage) scores. These cards of lots of words in common with no regard to uncommon
  keep_top_one_direction: 3                                 #There is a forward and backword score to find the n-cards that might only match in one direction (ie. a card contains two facts so does not match either duplicate)
Misc:
  folder: "anki_collection/"
  non_dupes_dict: bin/non_dupes.json
  template_col: bin/collection.anki2
  extension: "pkg"
  bin_size: 5000
  absolute_min_score: 25
  unimportant_words:
    - typically
    - typical
  synonyms: #the following will be replaced. Note that these are patterns and certain characters need to be escaped https://www.dataquest.io/blog/regex-cheatsheet/
    cause:
      - lead to
      - "="
      - results in
    increase:
      - a build up of
      - "↑"
      - build-up
      - higher
      - more
      - high
    decrease:
      - "↓"
      - deplete
      - diminished
      - lower
      - less
      - smaller amount
      - low
    unchange:
      - "↔"
      - no change
      - remains the same
      - unchanged
      - unchanging
    a:
      - a(n)
      - an
    beta:
      - "β"
      - 'Î²'
    alpha:
      - 'α'
      - "Î±"
    potassium:
      - "K\\+"
      - "K<sup>\\+</sup>"
    sodium:
      - "Na\\+"
      - "Na<sup>\\+</sup>"
    chloride:
      - "Cl-"
      - "Cl<sup>-</sup>"
